source 'https://rubygems.org'
ruby '2.2.4'

gem 'sinatra', '1.4.6', require: 'sinatra/base'
gem 'sinatra-contrib', '1.4.6'
gem 'rack-standards', '0.0.1'
gem 'i18n', '0.7.0'
gem 'rake', '10.4.2'
gem 'json', '1.8.3'
gem 'httpclient', '2.7.0.1'
gem 'patron', '0.5.0'
gem 'foreman', '0.78.0'
gem 'thin', '1.6.4'

# geocoding
gem 'geocoder', '1.2.14'
# languge
gem 'cld2', '1.0.3', require: 'cld'
# sentiment
gem 'sentimental', '1.0.4'
# dependencies
gem 'lowendinsight', github: 'ion-channel/lowendinsight', :branch => 'master'

# aws
gem 'aws-sdk', '2.2.9'

gem 'bundler', '>1.10.6'

group :test do
  gem 'minitest'
end
