[[constraint]]
  name = "github.com/ion-channel/ionic"
  revision = "ccc72d035b193a0b4cc0cbc42cf28a7295ebf774"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
