[[constraint]]
  name = "github.com/ion-channel/ionic"
  revision = "fcfe8246ff55a863c48f08d6d038ab2a772b08db"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
