---
  version: v1
  endpoint: https://api.ionchannel.io/
  token: access-token
  commands:
    - name: scanner
      usage: set of commands for effecting artifacts or source code
      subcommands:
        - name: scan-git
          usage: scan a git source code repository
          write: True
          flags:
            - name: name
              value:
              usage: the name of the source repository to effect
            - name: url
              value:
              usage: the location of the artifact or source
        - name: scan-svn
          usage: scan a subversion source code repository
          write: True
          flags:
            - name: name
              value:
              usage: the name of the source repository to effect
            - name: url
              value:
              usage: the location of the artifact or source
        - name: scan-artifact
          usage: scan an artifact
          write: True
          flags:
            - name: name
              value:
              usage: the name of the artifact to effect
            - name: url
              value:
              usage: the location of the artifact or source
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
