 # config.yaml
 #
 # Copyright (C) 2015 Selection Pressure LLC
 #
 # This software may be modified and distributed under the terms
 # of the MIT license.  See the LICENSE file for details.
---
  version: v1
  endpoint: https://api.ionchannel.io/
  token: apikey
  commands:
    # scanner
    - name: scanner
      usage: set of commands for effecting artifacts or source code
      subcommands:
        - name: scan-git
          url: /scanner/scanGit
          usage: scan a git source code repository
          post: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: url
              value:
              usage: URL
              required: True
        - name: analyze-project
          url: /scanner/analyzeProject
          usage: run an analysis on an Ion Channel project
          post: True
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
            - name: project-id
              value:
              usage: The id of the project the analysis resides
              required: True
              type: string
          args:
            - name: build-number
              value:
              usage: BUILDNUMBER
              required: True
        - name: get-analysis-status
          url: /scanner/getAnalysisStatus
          usage: returns the status data for a given analysis [id]
          post: False
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
            - name: project-id
              value:
              usage: The id of the project the analysis resides
              required: True
              type: string
          args:
            - name: id
              value:
              usage: ID
              required: True
        - name: add-scan-result
          url: /scanner/addScanResult
          usage: add the result of an external scan to an existing or new analysis
          post: True
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
            - name: project-id
              value:
              usage: The id of the project the analysis resides
              required: True
              type: string
            - name: analysis-id
              value:
              usage: The id of the analysis that the result will be added to
              required: True
              type: string
          args:
            - name: status
              value:
              usage: STATUS
              required: True
            - name: results
              value:
              usage: RESULTS
              required: True
              type: object
            - name: scan-type
              value:
              usage: SCAN_TYPE
              required: True
        - name: scan-artifact-url
          url: /scanner/scanArtifactUrl
          usage: scan an artifact from a remote url
          post: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: url
              value:
              usage: URL
              required: True
            - name: checksum
              value:
              usage: CHECKSUM
              required: True
        - name: get-scan
          url: /scanner/getScan
          usage: returns the status data for a given [id]
          post: False
          args:
            - name: id
              value:
              usage: ID
              required: True
        - name: scan-dependencies
          url: /scanner/scanDependencies
          usage: scan a file for a list of dependencies
          post: True
          flags:
            - name: type
              value:
              usage: The type of dependency file the file contents represents [gemfile|gemspec|package]
              required: True
              type: string
          args:
            - name: file
              type: file
              value:
              usage: path/to/dependency/file
              required: True
        - name: get-dependencies
          url: /scanner/getDependencies
          usage: returns the dependencies data for a given [id]
          post: False
          args:
            - name: id
              value:
              usage: ID
              required: True

    # airgap
    - name: airgap
      usage: set of commands for moving artifacts or source code
      subcommands:
        - name: push-artifact-url
          url: /airgap/pushArtifactUrl
          usage: push an artifact from a remote url
          post: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: url
              value:
              usage: URL
              required: True
            - name: checksum
              value:
              usage: CHECKSUM
              required: True
        - name: get-push
          url: /airgap/getPush
          usage: returns the status data for a given [id]
          post: False
          args:
            - name: id
              value:
              usage: ID
              required: True

    # metadata
    - name: metadata
      usage: set of commands for parsing metadata from text
      subcommands:
        - name: get-locations
          url: /metadata/getLocations
          usage: returns the locations parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
        - name: get-languages
          url: /metadata/getLanguages
          usage: returns the languages parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
        - name: get-licenses
          url: /metadata/getLicenses
          usage: returns the licenses parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
        - name: get-sentiment
          url: /metadata/getSentiment
          usage: returns the sentiment parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
    # ruleset
    - name: ruleset
      usage: set of commands for managing rulesets
      subcommands:
        - name: apply-ruleset
          url: /ruleset/applyRuleset
          usage: apply a rulset defined by [id] to a provided analysis' scan set
          post: true
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
          args:
            - name: id
              value:
              usage: ID
              required: True
          args:
            - name: scan-set
              value:
              usage: SCANSET
              type: object

        - name: create-ruleset
          url: /ruleset/createRuleset
          usage: create a rulset with the data provided
          post: true
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
          args:
            - name: id
              value:
              usage: ID
              required: True
            - name: name
              value:
              usage: NAME
              required: True
            - name: description
              value:
              usage: DESCRIPTION
              required: True
            - name: rules
              value:
              usage: RULES
              required: True
              type: array

        - name: get-ruleset
          url: /ruleset/getRuleset
          usage: get the values for a given ruleset id
          post: false
          flags:
            - name: account-id
              value:
              usage: The id of the account the ruleset is in
              required: True
              type: string
          args:
            - name: id
              value:
              usage: ID
              required: True

        - name: get-rulesets
          url: /ruleset/getRulesets
          usage: get all rulsets for an account
          post: false
          flags:
            - name: account-id
              value:
              usage: The id of the account for the rulesets
              required: True
              type: string

    # animal
    - name: animal
      usage: set of commands for querying raw analysis and scan data
      subcommands:
        - name: get-analysis
          url: /animal/getAnalysis
          usage: get an analysis for the provided account, project and analysis ids
          post: false
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
            - name: project-id
              value:
              usage: The id of the project the analysis resides
              required: True
              type: string
          args:
            - name: id
              value:
              usage: ID
              required: True

        - name: get-scan
          url: /animal/getScan
          usage: get a scan for the provided account, project, analysis and scan ids
          post: false
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
            - name: project-id
              value:
              usage: The id of the project the analysis resides
              required: True
              type: string
          args:
            - name: analysis-id
              value:
              usage: ANALYSISID
              required: True
            - name: id
              value:
              usage: ID
              required: True

        - name: get-analyses
          url: /animal/getAnalyses
          usage: get analyses for the provided account and project ids
          post: false
          flags:
            - name: account-id
              value:
              usage: The id of the account the analysis and project reside
              required: True
              type: string
            - name: project-id
              value:
              usage: The id of the project the analysis resides
              required: True
              type: string

    # vulnerability
    - name: vulnerability
      usage: set of commands for querying vulnerabilities
      subcommands:
        - name: get-vulnerabilities
          url: /vulnerability/getVulnerabilities
          usage: returns a list of vulnerabilities for a given query
          post: False
          flags:
            - name: limit
              value: 10
              usage: limit the amount of vulnerabilities returned, defaults to 10
              required: False
              type: string

            - name: offset
              value: 0
              usage: set the start index of the vulnerabilities returned, defaults to 0
              required: False
              type: string

            - name: text
              usage: query vulnerabilities using [TEXT]
              required: False
              type: bool
              args:
                - name: text
                  value:
                  usage: TEXT
                  required: True

            - name: id
              usage: query vulnerabilities using a vulnerability [ID]
              required: False
              type: bool
              args:
                - name: id
                  value:
                  usage: ID
                  required: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: version
              value:
              usage: VERSION
              required: False

# only for test
    - name: test
      usage: set of commands testing
      subcommands:
        - name: test1
          url: /
          usage: tests only
          post: False
          flags:
          - name: project
            usage: query vulnerabilities using [PROJECT]
            required: False
            type: bool
            args:
              - name: project
                value:
                usage: PROJECT
                required: True
          - name: id
            usage: query vulnerabilities using a vulnerability [ID]
            required: True
            type:
            args:
              - name: id
                value:
                usage: ID
                required: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
            - name: text2
              value:
              usage: TEXT2
              required: True
        - name: test2
          url: /test/getTest
          usage: tests only
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
            - name: othertext
              value:
              usage: OTHERTEXT
              required: False
            - name: text2
              value:
              usage: TEXT2
              required: True
        - name: test3
          url: /test/getTest
          usage: tests only
          post: True
          args:
        - name: test-json
          url: /test/getTest
          usage: tests only
          post: True
          args:
            - name: results
              value:
              usage: RESULTS
              type: object
              required: True
            - name: rules
              value:
              usage: RULES
              type: array
              required: True
