 # config.yaml
 #
 # Copyright (C) 2015 Selection Pressure LLC
 #
 # This software may be modified and distributed under the terms
 # of the MIT license.  See the LICENSE file for details.
---
  version: v1
  endpoint: https://api.ionchannel.io/
  token: apikey
  commands:
    - name: scanner
      usage: set of commands for effecting artifacts or source code
      subcommands:
        - name: scan-git
          url: /scanner/scanGit
          usage: scan a git source code repository
          post: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: url
              value:
              usage: URL
              required: True
        - name: scan-artifact-url
          url: /scanner/scanArtifactUrl
          usage: scan an artifact from a remote url
          post: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: url
              value:
              usage: URL
              required: True
            - name: checksum
              value:
              usage: CHECKSUM
              required: True
        - name: get-scan
          url: /scanner/getScan
          usage: returns the status data for a given [id]
          post: False
          args:
            - name: id
              value:
              usage: ID
              required: True
    - name: airgap
      usage: set of commands for moving artifacts or source code
      subcommands:
        - name: push-artifact-url
          url: /airgap/pushArtifactUrl
          usage: push an artifact from a remote url
          post: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: url
              value:
              usage: URL
              required: True
            - name: checksum
              value:
              usage: CHECKSUM
              required: True
        - name: get-push
          url: /airgap/getPush
          usage: returns the status data for a given [id]
          post: False
          args:
            - name: id
              value:
              usage: ID
              required: True
    - name: metadata
      usage: set of commands for parsing metadata from text
      subcommands:
        - name: get-locations
          url: /metadata/getLocations
          usage: returns the locations parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
        - name: get-languages
          url: /metadata/getLanguages
          usage: returns the languages parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
        - name: get-licenses
          url: /metadata/getLicenses
          usage: returns the licenses parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
        - name: get-sentiment
          url: /metadata/getSentiment
          usage: returns the sentiment parsed from the [text] input
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
    - name: vulnerabilities
      usage: set of commands for querying vulnerabilities
      subcommands:
        - name: get-vulnerabilities
          url: /vulnerabilities/getVulnerabilities
          usage: returns a list of vulnerabilities for a given query
          post: False
          flags:
            - name: text
              usage: query vulnerabilities using [TEXT]
              required: False
              type: bool
              args:
                - name: text
                  value:
                  usage: TEXT
                  required: True
            - name: id
              usage: query vulnerabilities using a vulnerability [ID]
              required: False
              type:
              args:
                - name: id
                  value:
                  usage: ID
                  required: True
          args:
            - name: project
              value:
              usage: PROJECT
              required: True
            - name: version
              value:
              usage: VERSION
              required: False

# only for test
    - name: test
      usage: set of commands testing
      subcommands:
        - name: test1
          url: /
          usage: tests only
          post: False
          flags:
          - name: project
            usage: query vulnerabilities using [PROJECT]
            required: False
            type: bool
            args:
              - name: project
                value:
                usage: PROJECT
                required: True
          - name: id
            usage: query vulnerabilities using a vulnerability [ID]
            required: True
            type:
            args:
              - name: id
                value:
                usage: ID
                required: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
            - name: text2
              value:
              usage: TEXT2
              required: True
        - name: test2
          url: /test/getTest
          usage: tests only
          post: True
          args:
            - name: text
              value:
              usage: TEXT
              required: True
            - name: othertext
              value:
              usage: OTHERTEXT
              required: False
            - name: text2
              value:
              usage: TEXT2
              required: True
        - name: test3
          url: /test/getTest
          usage: tests only
          post: True
          args:
