 # config.yaml
 #
 # Copyright (C) 2015 Selection Pressure LLC
 #
 # This software may be modified and distributed under the terms
 # of the MIT license.  See the LICENSE file for details.
---
  version: v1
  endpoint: https://api.ionchannel.io/
  token: apikey
  commands:
    - name: scanner
      usage: set of commands for effecting artifacts or source code
      subcommands:
        - name: scan-git
          url: /scanner/scan-git
          usage: scan a git source code repository
          post: True
          flags:
            - name: name
              value:
              usage: the name of the source repository to effect
            - name: url
              value:
              usage: the location of the artifact or source
        # - name: scan-artifact-file
        #   url: /scanner/artifact/file
        #   usage: scan an artifact from a local path
        #   post: True
        #   flags:
        #     - name: name
        #       value:
        #       usage: the name of the source repository to effect
        #     - name: path
        #       value:
        #       usage: the location of the artifact
        #     - name: checksum
        #       value:
        #       usage: the checksum calculated from the artifact
        - name: scan-artifact-url
          url: /scanner/scan-artifact-url
          usage: scan an artifact from a remote url
          post: True
          flags:
            - name: name
              value:
              usage: the name of the artifact to effect
            - name: url
              value:
              usage: the location of the artifact
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
        - name: get-scan
          url: /scanner/get-scan/{{ .Scanid }}
          usage: returns the status data for a given [scanid]
          post: False
          flags:
            - name: scanid
              value:
              usage: the id of the scan to query
    - name: airgap
      usage: set of commands for moving artifacts or source code
      subcommands:
        - name: push-artifact-url
          url: /airgap/push-artifact-url
          usage: push an artifact from a remote url
          post: True
          flags:
            - name: name
              value:
              usage: the name of the artifact to push
            - name: url
              value:
              usage: the location of the artifact
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
        - name: get-push
          url: /airgap/get-push/{{ .Airgapid }}
          usage: returns the status data for a given [airgapid]
          post: False
          flags:
            - name: airgapid
              value:
              usage: the id of the pushed artifact
