 # config.yaml
 #
 # Copyright (C) 2015 Selection Pressure LLC
 #
 # This software may be modified and distributed under the terms
 # of the MIT license.  See the LICENSE file for details.
---
  version: v1
  endpoint: https://api.ionchannel.io/
  token: apikey
  commands:
    - name: scanner
      usage: set of commands for effecting artifacts or source code
      subcommands:
        - name: scan-git
          url: /scanner/git
          usage: scan a git source code repository
          post: True
          flags:
            - name: name
              value:
              usage: the name of the source repository to effect
            - name: url
              value:
              usage: the location of the artifact or source
        - name: scan-file-artifact
          url: /scanner/artifact/file
          usage: scan an artifact from a local path
          post: True
          flags:
            - name: name
              value:
              usage: the name of the source repository to effect
            - name: path
              value:
              usage: the location of the artifact
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
        - name: scan-url-artifact
          url: /scanner/artifact/url
          usage: scan an artifact from a remote url
          post: True
          flags:
            - name: name
              value:
              usage: the name of the artifact to effect
            - name: url
              value:
              usage: the location of the artifact
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
        - name: scan-status
          url: /scanner/status/{{ .Scanid }}
          usage: returns the status data for a given [scan-id]
          post: False
          flags:
            - name: scanid
              value:
              usage: the id of the scan to query
    - name: airgap
      usage: set of commands for moving artifacts or source code
