 # config.yaml
 #
 # Copyright (C) 2015 Selection Pressure LLC
 #
 # This software may be modified and distributed under the terms
 # of the MIT license.  See the LICENSE file for details.
---
  version: v1
  endpoint: https://api.ionchannel.io/
  token: apikey
  commands:
    - name: scanner
      usage: set of commands for effecting artifacts or source code
      subcommands:
        - name: scan-git
          url: /scanner/scanGit
          usage: scan a git source code repository
          post: True
          flags:
            - name: project
              value:
              usage: the name of the project source repository to effect
            - name: url
              value:
              usage: the location of the artifact or source
        - name: scan-artifact-url
          url: /scanner/scanArtifactUrl
          usage: scan an artifact from a remote url
          post: True
          flags:
            - name: project
              value:
              usage: the name of the project for the artifact to effect
            - name: url
              value:
              usage: the location of the artifact
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
        - name: get-scan
          url: /scanner/getScan
          usage: returns the status data for a given [id]
          post: False
          flags:
            - name: id
              value:
              usage: the id of the scan to query
    - name: airgap
      usage: set of commands for moving artifacts or source code
      subcommands:
        - name: push-artifact-url
          url: /airgap/pushArtifactUrl
          usage: push an artifact from a remote url
          post: True
          flags:
            - name: project
              value:
              usage: the name of the project for the artifact to push
            - name: url
              value:
              usage: the location of the artifact
            - name: checksum
              value:
              usage: the checksum calculated from the artifact
        - name: get-push
          url: /airgap/getPush
          usage: returns the status data for a given [id]
          post: False
          flags:
            - name: id
              value:
              usage: the id of the pushed artifact
